version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dev:
        dependency-type: "development"
      prod:
        dependency-type: "production"
  - package-ecosystem: "npm"
    directory: "/docs-fd"
    schedule:
      interval: "weekly"
    groups:
      dev:
        dependency-type: "development"
      prod:
        dependency-type: "production"
  - package-ecosystem: "npm"
    directory: "/examples/basic"
    schedule:
      interval: "weekly"
    groups:
      dev:
        dependency-type: "development"
      prod:
        dependency-type: "production"
  - package-ecosystem: "npm"
    directory: "/examples/supertrader"
    schedule:
      interval: "weekly"
    groups:
      dev:
        dependency-type: "development"
      prod:
        dependency-type: "production"
