version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "inversify"
        versions: ["7.x"]
  - package-ecosystem: "npm"
    directory: "/docs-fd"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/examples/basic"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "inversify"
        versions: ["7.x"]
  - package-ecosystem: "npm"
    directory: "/examples/supertrader"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "inversify"
        versions: ["7.x"]
